///////////////////////////////////
// This file is automatically generated from the keys of 'en.json'
// Do not edit it manually as it will be overwritten at the next pull/merge
// If it gets out of sync with your translations, you can run 'yarn i18n' to update it

export const i18nKeys = {
  "general": {
    "showToast": "general.showToast",
    "infoToast": "general.infoToast"
  },
  "home": {
    "hello": "home.hello",
    "introduction": "home.introduction",
    "topFeature": "home.topFeature",
    "topFeature_plural": "home.topFeature_plural"
  }
}
